services:
  - type: web
    name: smart-waste-management
    env: python
    buildCommand: |
      cd smart-waste-management
      pip install -r requirements.txt
    startCommand: |
      cd smart-waste-management
      gunicorn waste_management.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DJANGO_SETTINGS_MODULE
        value: waste_management.settings_prod
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        fromDatabase:
          name: smart-waste-db
          property: connectionString

databases:
  - name: smart-waste-db
    databaseName: smart_waste_db
    user: smart_waste_user
    plan: free 