# Generated by Django 4.2.20 on 2025-05-10 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=100)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "routes_bin_table",
            },
        ),
        migrations.CreateModel(
            name="CollectionRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("collection_day", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("point_a_latitude", models.FloatField(blank=True, null=True)),
                ("point_a_longitude", models.FloatField(blank=True, null=True)),
                ("point_b_latitude", models.FloatField(blank=True, null=True)),
                ("point_b_longitude", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routes_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RouteBin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collection_order", models.PositiveIntegerField(default=1)),
                (
                    "bin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_bin_links",
                        to="routes.bin",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_bins",
                        to="routes.collectionroute",
                    ),
                ),
            ],
            options={
                "db_table": "routes_route_bin",
                "ordering": ["collection_order"],
                "unique_together": {("route", "bin")},
            },
        ),
        migrations.AddField(
            model_name="collectionroute",
            name="bins",
            field=models.ManyToManyField(
                related_name="collection_routes",
                through="routes.RouteBin",
                to="routes.bin",
            ),
        ),
    ]
