# Generated by Django 4.2.20 on 2025-05-11 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bins", "0004_alter_wastebin_table"),
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionroute",
            name="bins",
            field=models.ManyToManyField(
                related_name="collection_routes",
                through="routes.RouteBin",
                to="bins.wastebin",
            ),
        ),
        migrations.AlterField(
            model_name="routebin",
            name="bin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="route_bin_links",
                to="bins.wastebin",
            ),
        ),
    ]
