# Generated by Django 4.2.20 on 2025-05-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0002_alter_collectionroute_bins_alter_routebin_bin"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionroute",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
