# Generated by Django 5.2 on 2025-05-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WasteBin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=50, unique=True)),
                (
                    "bin_type",
                    models.CharField(
                        choices=[
                            ("general", "General Waste"),
                            ("recyclable", "Recyclable Waste"),
                            ("hazardous", "Hazardous Waste"),
                            ("organic", "Organic Waste"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("empty", "Empty"),
                            ("half", "Half Full"),
                            ("full", "Full"),
                            ("overflow", "Overflowing"),
                        ],
                        default="empty",
                        max_length=20,
                    ),
                ),
                ("last_collected", models.DateTimeField(blank=True, null=True)),
                (
                    "collection_frequency",
                    models.PositiveIntegerField(help_text="Days between collections"),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(help_text="Capacity in liters"),
                ),
                ("installed_date", models.DateField(auto_now_add=True)),
            ],
            options={
                "ordering": ["identifier"],
            },
        ),
    ]
