# Generated by Django 5.2 on 2025-05-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bins", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wastebin",
            options={},
        ),
        migrations.RemoveField(
            model_name="wastebin",
            name="capacity",
        ),
        migrations.RemoveField(
            model_name="wastebin",
            name="collection_frequency",
        ),
        migrations.RemoveField(
            model_name="wastebin",
            name="installed_date",
        ),
        migrations.AlterField(
            model_name="wastebin",
            name="bin_type",
            field=models.CharField(
                choices=[
                    ("recyclable", "Recyclable"),
                    ("organic", "Organic"),
                    ("general", "General"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="wastebin",
            name="current_status",
            field=models.CharField(
                choices=[("empty", "Empty"), ("half", "Half Full"), ("full", "Full")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="wastebin",
            name="identifier",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="wastebin",
            name="latitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="wastebin",
            name="longitude",
            field=models.FloatField(),
        ),
    ]
