# Generated by Django 5.2 on 2025-05-07 03:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("bins", "0002_alter_wastebin_options_remove_wastebin_capacity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wastebin",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
