# Generated by Django 4.2.20 on 2025-05-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="illegaldumpingreport",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="%Y/%m/%d/"),
        ),
    ]
